[package]
name = "devefi-icrc-ledger"
version = "1.1.5"
description = "Local ICRC ledger syncing with remote ledger"
repository = "https://github.com/Neutrinomic/devefi_icrc_ledger"
keywords = [ ]
license = "MIT"

[dependencies]
vector = "0.2.0"
map = "9.0.1"
swb = "1.1.1"
stableheapbtreemap = "1.5.0"

[dev-dependencies]
itertools = "0.2.1"
