[package]
name = "devefi-icrc-ledger"
version = "1.0.8"
description = "Local ICRC ledger syncing with remote ledger"
repository = "https://github.com/Neutrinomic/devefi_icrc_ledger"
keywords = [ ]
license = "MIT"

[dependencies]
vector = "0.2.0"
map = "9.0.1"
devefi-icrc-sender = "1.0.6"
devefi-icrc-reader = "1.0.5"
swb = "1.1.1"

[dev-dependencies]
itertools = "0.2.1"
